Fix actions
sourcefuse/terraform-aws-arc-bootstrap pull request #13
Opened 2022-08-05 19:17 UTC by chrisdeffer

2022-08-30 15:51 UTC, tsaucier-sf approved these changes

2022-09-29 21:18 UTC, mayank0202 approved these changes

2022-09-30 10:51 UTC, tsaucier-sf requested changes

2022-09-30 10:51 UTC, tsaucier-sf commented on main.tf
> +   required_version = ">= 1.0.8"
Fix indentation

2022-09-30 10:54 UTC, mayank0202 commented on main.tf
> +   required_version = ">= 1.0.8"
I used terraform fmt .. ok will do again @tsaucier-sf

2022-09-30 10:56 UTC, tsaucier-sf approved these changes

2022-09-30 12:36 UTC, jamescrowley321 approved these changes

2022-09-30 12:36 UTC, merged