updated the Bootstrap Module to be in a working version
sourcefuse/terraform-aws-arc-bootstrap pull request #23
Opened 2023-07-19 19:29 UTC by mayank0202

First of all I have removed the logging config from terraform as its require a target bucket name which should be different so if we want logging then we should create a separate bucket else apply will give error 

so 1.0.2 is in working condition but after that all versions give error of logging buckets so thats why removed and tested with an example

2023-07-19 19:36 UTC, tsaucier-sf requested changes

2023-07-19 19:36 UTC, tsaucier-sf commented on example/dev.tfvars
> +bucket_name              = "arc-mayank-poc"
Change to something generic please

2023-07-19 19:36 UTC, tsaucier-sf commented on example/dev.tfvars
> +dynamodb_name            = "arc-mayank-poc"
Change to something generic please

2023-07-19 19:40 UTC, mayank0202 commented on example/dev.tfvars
> +bucket_name              = "arc-mayank-poc"
sorry i just was in a hurry to shutdown :sweat_smile:
Done

2023-07-20 01:22 UTC, tsaucier-sf approved these changes

2023-07-20 04:05 UTC, merged